apiVersion: v1
kind: Service
metadata:
  name: net-attach-def-admission-controller-service
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: net-attach-def-admission-controller
